#ifndef ERRNO_HPP
# define ERRNO_HPP

#define ERRNO_OFFSET 2000

enum PTErrorCode
{
    ER_SUCCESS = 0,
    PT_ERR_QUEUE_FULL,
    PT_ERR_MUTEX_NULLPTR,
    PT_ERR_MUTEX_OWNER,
	PT_ERR_ALRDY_LOCKED,
    SHARED_PTR_NULL_PTR,
    SHARED_PTR_OUT_OF_BOUNDS,
    SHARED_PTR_ALLOCATION_FAILED,
    SHARED_PTR_INVALID_OPERATION,
    MAP_ALLOCATION_FAILED,
    MAP_KEY_NOT_FOUND,
	FILE_INVALID_FD,
	FT_EINVAL,
	STRING_MEM_ALLOC_FAIL,
	VECTOR_ALLOC_FAIL,
	VECTOR_OUT_OF_BOUNDS,
	VECTOR_INVALID_PTR,
	VECTOR_CRITICAL_ERROR,
	VECTOR_INVALID_OPERATION,
	FT_EALLOC,
	FT_ETERM,
};

const char* ft_strerror(int error_code);

extern thread_local int ft_errno;

#endif
