#ifndef ARMOR_H
# define ARMOR_H

#include <stddef.h>
#include "character.hpp"
#include "identification.hpp"
#include "initialize.hpp"
#include "libft/CPP_class/nullptr.hpp"

static const t_equipment_id LEATHER_ARMOR =
{
	.name = "leather armor",
	.projectile_name = ft_nullptr,
	.equipment_id = LEATHER_ARMOR_ID,
	.action_01 = INITIALIZE_EQUIPMENT_ACTION,
	.action_02 = INITIALIZE_EQUIPMENT_ACTION,
	.attack = INITIALIZE_EQUIPMENT_ACTION,
	.skill_mod = INITIALIZE_SKILLS,
	.resistance = INITIALIZE_RESISTANCE,
	.flat_dr = INITIALIZE_RESISTANCE,
	.skill_advantage = INITIALIZE_SKILLS,
	.save = INITIALIZE_SAVES,
	.save_advantage = INITIALIZE_SAVES,
	.crit_attack_fail_bonus = 0,
	.crit_attack_succes_bonus = 0,
	.type = ATYPE_LEATHER,
	.dex_ac_max_bonus = 2,
	.ac = 2,
	.str = 0,
	.dex = 0,
	.con = 0,
	.inte = 0,
	.wis = 0,
	.cha = 0,
	.initiative = 0,
	.effect_id = 0,
	.effect_type = 0,
	.effect_dice_amount = 0,
	.effect_dice_faces = 0,
	.bonus_mod = 0,
	.slot = SLOT_ARMOR,
};

static const t_equipment_id WOLF_PELT =
{
	.name = "wolf pelt",
	.projectile_name = ft_nullptr,
	.equipment_id = LEATHER_ARMOR_ID,
	.action_01 = INITIALIZE_EQUIPMENT_ACTION,
	.action_02 = INITIALIZE_EQUIPMENT_ACTION,
	.attack = INITIALIZE_EQUIPMENT_ACTION,
	.skill_mod = INITIALIZE_SKILLS,
	.resistance = INITIALIZE_RESISTANCE,
	.flat_dr = INITIALIZE_RESISTANCE,
	.skill_advantage = INITIALIZE_SKILLS,
	.save = INITIALIZE_SAVES,
	.save_advantage = INITIALIZE_SAVES,
	.crit_attack_fail_bonus = 0,
	.crit_attack_succes_bonus = 0,
	.type = ATYPE_LEATHER,
	.dex_ac_max_bonus = 4,
	.ac = 3,
	.str = 0,
	.dex = 0,
	.con = 0,
	.inte = 0,
	.wis = 0,
	.cha = 0,
	.initiative = 0,
	.effect_id = 0,
	.effect_type = 0,
	.effect_dice_amount = 0,
	.effect_dice_faces = 0,
	.bonus_mod = 0,
	.slot = SLOT_ARMOR,
};

static const t_equipment_id GHOST_ARMOR =
{
	.name = "ghost armor",
	.projectile_name = ft_nullptr,
	.equipment_id = LEATHER_ARMOR_ID,
	.action_01 = INITIALIZE_EQUIPMENT_ACTION,
	.action_02 = INITIALIZE_EQUIPMENT_ACTION,
	.attack = INITIALIZE_EQUIPMENT_ACTION,
	.skill_mod = INITIALIZE_SKILLS,
	.resistance =
	{
		.acid = 0,
		.bludgeoning = 50,
		.cold = 0,
		.fire = 0,
		.force = WTYPE_QUARTERSTAFF,
		.lightning = 0,
		.necrotic = 100,
		.piercing = 50,
		.poison = 0,
		.psychic = 0,
		.radiant = 0,
		.slashing = 50,
		.thunder = 0,
	},
	.flat_dr = INITIALIZE_RESISTANCE,
	.skill_advantage = INITIALIZE_SKILLS,
	.save = INITIALIZE_SAVES,
	.save_advantage = INITIALIZE_SAVES,
	.crit_attack_fail_bonus = 0,
	.crit_attack_succes_bonus = 0,
	.type = ATYPE_LEATHER,
	.dex_ac_max_bonus = 0,
	.ac = 5,
	.str = 0,
	.dex = 0,
	.con = 0,
	.inte = 0,
	.wis = 0,
	.cha = 0,
	.initiative = 0,
	.effect_id = 0,
	.effect_type = 0,
	.effect_dice_amount = 0,
	.effect_dice_faces = 0,
	.bonus_mod = 0,
	.slot = SLOT_ARMOR,
};

static const t_equipment_id STEEL_ARMOR =
{
	.name = "steel armor",
	.projectile_name = ft_nullptr,
	.equipment_id = STEEL_ARMOR_ID,
	.action_01 = INITIALIZE_EQUIPMENT_ACTION,
	.action_02 = INITIALIZE_EQUIPMENT_ACTION,
	.attack = INITIALIZE_EQUIPMENT_ACTION,
	.skill_mod = INITIALIZE_SKILLS,
	.resistance = INITIALIZE_RESISTANCE,
	.flat_dr = INITIALIZE_RESISTANCE,
	.skill_advantage = INITIALIZE_SKILLS,
	.save = INITIALIZE_SAVES,
	.save_advantage = INITIALIZE_SAVES,
	.crit_attack_fail_bonus = 0,
	.crit_attack_succes_bonus = 0,
	.type = ATYPE_LEATHER,
	.dex_ac_max_bonus = 2,
	.ac = 6,
	.str = 0,
	.dex = 0,
	.con = 0,
	.inte = 0,
	.wis = 0,
	.cha = 0,
	.initiative = 0,
	.effect_id = 0,
	.effect_type = 0,
	.effect_dice_amount = 0,
	.effect_dice_faces = 0,
	.bonus_mod = 0,
	.slot = SLOT_ARMOR,
};

#endif
