#ifndef IDENTIFICATION_H
# define IDENTIFICATION_H

typedef enum {
    WTYPE_CLUB = 1,
    WTYPE_DAGGER,
    WTYPE_GREATCLUB,
    WTYPE_HANDAXE,
    WTYPE_JAVELIN,
    WTYPE_LIGHT_HAMMER,
    WTYPE_MACE,
    WTYPE_QUARTERSTAFF,
    WTYPE_SICKLE,
    WTYPE_SPEAR,
    WTYPE_LIGHT_CROSSBOW,
    WTYPE_DART,
    WTYPE_SHORTBOW,
    WTYPE_SLING,
    WTYPE_BATTLEAXE,
    WTYPE_FLAIL,
    WTYPE_GLAIVE,
    WTYPE_GREATSWORD,
    WTYPE_HALBERD,
    WTYPE_LANCE,
    WTYPE_LONGSWORD,
    WTYPE_MAUL,
    WTYPE_MORNINGSTAR,
    WTYPE_PIKE,
    WTYPE_RAPIER,
    WTYPE_SCIMITAR,
    WTYPE_SHORTSWORD,
    WTYPE_TRIDENT,
    WTYPE_WAR_PICK,
    WTYPE_WARHAMMER,
    WTYPE_WHIP,
    WTYPE_BLOWGUN,
    WTYPE_HAND_CROSSBOW,
    WTYPE_HEAVY_CROSSBOW,
    WTYPE_LONGBOW,
    WTYPE_NET,
    WTYPE_WAND,

	WTYPE_CLAW,
    
    ATYPE_PADDED = 10001,
    ATYPE_LEATHER,
    ATYPE_STUDDED_LEATHER,
    ATYPE_HIDE,
    ATYPE_CHAIN_SHIRT,
    ATYPE_SCALE_MAIL,
    ATYPE_BREASTPLATE,
    ATYPE_HALF_PLATE,
    ATYPE_RING_MAIL,
    ATYPE_CHAIN_MAIL,
    ATYPE_SPLINT,
    ATYPE_PLATE,
    ATYPE_SHIELD,

    STEEL_SWORD_ID = 20001,
	STEEL_BATTLE_AXE_ID,
    WOODEN_BOW_ID,
	WOODEN_CLUB_ID,
    CHAOS_WAND_ID,
	CLAW_ID,

    LEATHER_ARMOR_ID = 30001,
} ItemID;

typedef enum e_equipment_slot
{
	SLOT_NONE				= 0,
	SLOT_WEAPON				= 1 << 0,
	SLOT_OFFHAND_WEAPON		= 1 << 1,
	SLOT_RANGED_WEAPON		= 1 << 2,
	SLOT_ARMOR				= 1 << 3,
	SLOT_HELMET				= 1 << 4,
	SLOT_SHIELD				= 1 << 5,
	SLOT_BOOTS				= 1 << 6,
	SLOT_GLOVES				= 1 << 7,
	SLOT_AMULET				= 1 << 8,
	SLOT_RING_01			= 1 << 9,
	SLOT_RING_02			= 1 << 10,
	SLOT_BELT				= 1 << 11,
	SLOT_TWO_HANDED_WEAPON	= 1 << 12,
}	t_equipment_slot;

# define HUNTERS_MARK_ID 1
# define HUNTERS_MARK_NAME "hunters mark"
# define BLESS_ID 2
# define BLESS_NAME "bless"
# define CHAOS_ARMOR_ID 3
# define CHAOS_ARMOR_NAME "chaos_armor"

# define DAMAGE_TYPE_BLUDGEONING	"bludgeoning"
# define DAMAGE_TYPE_PIERCING		"piercing"
# define DAMAGE_TYPE_SLASHING		"slashing"
# define DAMAGE_TYPE_FIRE			"fire"
# define DAMAGE_TYPE_COLD			"cold"
# define DAMAGE_TYPE_LIGHTNING		"lightning"
# define DAMAGE_TYPE_ACID			"acid"
# define DAMAGE_TYPE_POISON			"poison"
# define DAMAGE_TYPE_FORCE			"force"
# define DAMAGE_TYPE_RADIANT		"radiant"
# define DAMAGE_TYPE_NECROTIC		"necrotic"
# define DAMAGE_TYPE_THUNDER		"thunder"
# define DAMAGE_TYPE_PSYCHIC		"psychic"

# define STAT_STR "strength"
# define STAT_DEX "dexterity"
# define STAT_CON "constitution"
# define STAT_INT "intelligence"
# define STAT_WIS "wisdom"
# define STAT_CHA "charisma"

# define FINESSE "finesse"

#define DATA_FOLDER "data"
#define PREFIX_TO_SKIP "data--"
#define EXCLUDE_PREFIX "pc--"
#define PC_PREFIX "pc--"

#define HEALTH_KEY "HEALTH="
#define TEMP_HP_KEY "TEMP_HP="
#define STR_KEY "STR="
#define DEX_KEY "DEX="
#define CON_KEY "CON="
#define INT_KEY "INT="
#define WIS_KEY "WIS="
#define CHA_KEY "CHA="
#define TURN_KEY "TURN="
#define INITIATIVE_KEY "INITIATIVE="
#define BLESS_DUR_KEY "BLESS_DUR="
#define PHASE_KEY "PHASE="
#define CONCENTRATION_KEY "CONCENTRATION="

#define HUNTERS_MARK_AMOUNT_KEY "HUNTERS_MARK_AMOUNT="
#define HUNTERS_MARK_CASTER_KEY "HUNTERS_MARK_CASTER="
#define CHAOS_ARMOR_DURATION_KEY "CHAOS_ARMOR_DURATION="
#define PRONE_KEY "PRONE="
#define BLINDED_KEY "BLINDED="

#define LIGHTNING_STRIKE_DUR_KEY "LIGHTNING_STRIKE_DUR="
#define PROTECTIVE_WINDS_DUR_KEY "PROTECTIVE_WINDS_DUR="
#define ACID_RESISTANCE_KEY "ACID_RESISTANCE="
#define BLUDGEONING_RESISTANCE_KEY "BLUDGEONING_RESISTANCE="
#define COLD_RESISTANCE_KEY "COLD_RESISTANCE="
#define FIRE_RESISTANCE_KEY "FIRE_RESISTANCE="
#define FORCE_RESISTANCE_KEY "FORCE_RESISTANCE="
#define LIGHTNING_RESISTANCE_KEY "LIGHTNING_RESISTANCE="
#define NECROTIC_RESISTANCE_KEY "NECROTIC_RESISTANCE="
#define PIERCING_RESISTANCE_KEY "PIERCING_RESISTANCE="
#define POISON_RESISTANCE_KEY "POISON_RESISTANCE="
#define PSYCHIC_RESISTANCE_KEY "PSYCHIC_RESISTANCE="
#define RADIANT_RESISTANCE_KEY "RADIANT_RESISTANCE="
#define SLASHING_RESISTANCE_KEY "SLASHING_RESISTANCE="
#define THUNDER_RESISTANCE_KEY "THUNDER_RESISTANCE="

#define CONC_TARGETS_KEY "CONC_TARGETS="
#define CONC_SPELL_ID_KEY "CONC_SPELL_ID="
#define CONC_DICE_AMOUNT_KEY "CONC_DICE_AMOUNT="
#define CONC_DICE_FACES_KEY "CONC_DICE_FACES="
#define CONC_BASE_MOD_KEY "CONC_BASE_MOD="
#define CONC_DURATION_KEY "CONC_DURATION="

#define FLAME_GEYSER_DURATION_KEY "FLAME_GEYSER_DURATION="
#define FLAME_GEYSER_AMOUNT_KEY "FLAME_GEYSER_AMOUNT="
#define FLAME_GEYSER_CLOSE_TO_TOWER_D_KEY "FLAME_GEYSER_CLOSE_TO_TOWER_D="
#define FLAME_GEYSER_TOWER_EXPLODE_D_KEY "FLAME_GEYSER_TOWER_EXPLODE_D="

#define METEOR_STRIKE_DURATION_KEY "METEOR_STRIKE_DURATION="
#define METEOR_STRIKE_ONE_TARGET_D_KEY "METEOR_STRIKE_ONE_TARGET_D="
#define METEOR_STRIKE_TWO_TARGETS_D_KEY "METEOR_STRIKE_TWO_TARGETS_D="
#define METEOR_STRIKE_THREE_TARGETS_D_KEY "METEOR_STRIKE_THREE_TARGETS_D="
#define METEOR_STRIKE_FOUR_TARGETS_D_KEY "METEOR_STRIKE_FOUR_TARGETS_D="
#define METEOR_STRIKE_FIVE_TARGETS_D_KEY "METEOR_STRIKE_FIVE_TARGETS_D="
#define METEOR_STRIKE_TARGET_KEY "METEOR_STRIKE_TARGET="

#define LIGHTNING_STRIKE_DURATION_KEY "LIGHTNING_STRIKE_DURATION="
#define LIGHTNING_STRIKE_AMOUNT_KEY "LIGHTNING_STRIKE_AMOUNT="
#define LIGHTNING_STRIKE_DISTANCE_KEY "LIGHTNING_STRIKE_DISTANCE="
#define LIGHTNING_STRIKE_DICE_AMOUNT_KEY "LIGHTNING_STRIKE_DICE_AMOUNT="
#define LIGHTNING_STRIKE_DICE_FACES_KEY "LIGHTNING_STRIKE_DICE_FACES="
#define LIGHTNING_STRIKE_EXTRA_DAMAGE_KEY "LIGHTNING_STRIKE_EXTRA_DAMAGE="

#define LIGHTNING_STRIKEV2_DURATION_KEY "LIGHTNING_STRIKEV2_DURATION="
#define LIGHTNING_STRIKEV2_AMOUNT_KEY "LIGHTNING_STRIKEV2_AMOUNT="
#define LIGHTNING_STRIKEV2_DISTANCE_KEY "LIGHTNING_STRIKEV2_DISTANCE="
#define LIGHTNING_STRIKEV2_DICE_AMOUNT_KEY "LIGHTNING_STRIKEV2_DICE_AMOUNT="
#define LIGHTNING_STRIKEV2_DICE_FACES_KEY "LIGHTNING_STRIKEV2_DICE_FACES="
#define LIGHTNING_STRIKEV2_EXTRA_DAMAGE_KEY "LIGHTNING_STRIKEV2_EXTRA_DAMAGE="

#define EARTH_POUNCE_ACTIVE_KEY "EARTH_POUNCE_ACTIVE="
#define EARTH_POUNCE_BASE_DAMAGE_KEY "EARTH_POUNCE_BASE_DAMAGE="
#define EARTH_POUNCE_TARGET_ID_KEY "EARTH_POUNCE_TARGET_ID="

#define ARCANE_POUNCE_ACTIVE_KEY "ARCANE_POUNCE_ACTIVE="
#define ARCANE_POUNCE_MAGIC_DAMAGE_KEY "ARCANE_POUNCE_MAGIC_DAMAGE="
#define ARCANE_POUNCE_EREA_DAMAGE_KEY "ARCANE_POUNCE_EREA_DAMAGE="
#define ARCANE_POUNCE_TARGET_ID_KEY "ARCANE_POUNCE_TARGET_ID="

#endif
