#ifndef MELEE_WEAPONS_H
# define MELEE_WEAPONS_H

#include <stddef.h>
#include "character.hpp"
#include "identification.hpp"
#include "initialize.hpp"
#include "libft/CPP_class/nullptr.hpp"

void	ft_weapon_attack(t_char *info, t_equipment_id *weapon, int offhand);

static const t_equipment_id STEEL_SWORD =
{
	.name = "steel sword",
	.projectile_name = ft_nullptr,
	.equipment_id = STEEL_SWORD_ID,
	.action_01 = INITIALIZE_EQUIPMENT_ACTION,
	.action_02 = INITIALIZE_EQUIPMENT_ACTION,
	.attack = {
		.function = ft_weapon_attack,
		.damage_type = DAMAGE_TYPE_SLASHING,
		.stat = FINESSE,
		.effect_type = 0,
		.effect_dice_amount = 1,
		.effect_dice_faces = 8,
		.effect_secund_dice_amount = 1,
		.effect_secund_dice_faces = 6,
		.bonus_mod = 0,
	},
	.skill_mod = INITIALIZE_SKILLSM,
	.resistance = INITIALIZE_RESISTANCE,
	.flat_dr = INITIALIZE_RESISTANCE,
	.skill_advantage = INITIALIZE_SKILLSM,
	.save = INITIALIZE_SAVES,
	.save_advantage = INITIALIZE_SAVES,
	.type = WTYPE_SHORTSWORD,
	.dex_ac_max_bonus = 0,
	.ac = 0,
	.str = 0,
	.dex = 0,
	.con = 0,
	.inte = 0,
	.wis = 0,
	.cha = 0,
	.initiative = 0,
	.effect_type = 0,
	.effect_dice_amount = 0,
	.effect_dice_faces = 0,
	.bonus_mod = 0,
	.slot = SLOT_WEAPON | SLOT_OFFHAND_WEAPON,
};

static const t_equipment_id STEEL_BATTLE_AXE =
{
	.name = "steel battle axe",
	.projectile_name = ft_nullptr,
	.equipment_id = STEEL_BATTLE_AXE_ID,
	.action_01 = INITIALIZE_EQUIPMENT_ACTION,
	.action_02 = INITIALIZE_EQUIPMENT_ACTION,
	.attack = {
		.function = ft_weapon_attack,
		.damage_type = DAMAGE_TYPE_SLASHING,
		.stat = STAT_STR,
		.effect_type = 0,
		.effect_dice_amount = 1,
		.effect_dice_faces = 10,
		.effect_secund_dice_amount = 1,
		.effect_secund_dice_faces = 8,
		.bonus_mod = 0,
	},
	.skill_mod = INITIALIZE_SKILLSM,
	.resistance = INITIALIZE_RESISTANCE,
	.flat_dr = INITIALIZE_RESISTANCE,
	.skill_advantage = INITIALIZE_SKILLSM,
	.save = INITIALIZE_SAVES,
	.save_advantage = INITIALIZE_SAVES,
	.type = WTYPE_BATTLEAXE,
	.dex_ac_max_bonus = 0,
	.ac = 0,
	.str = 0,
	.dex = 0,
	.con = 0,
	.inte = 0,
	.wis = 0,
	.cha = 0,
	.initiative = 0,
	.effect_type = 0,
	.effect_dice_amount = 0,
	.effect_dice_faces = 0,
	.bonus_mod = 0,
	.slot = SLOT_WEAPON | SLOT_OFFHAND_WEAPON,
};

static const t_equipment_id WOODEN_CLUB =
{
	.name = "wooden club",
	.projectile_name = ft_nullptr,
	.equipment_id = WOODEN_CLUB_ID,
	.action_01 = INITIALIZE_EQUIPMENT_ACTION,
	.action_02 = INITIALIZE_EQUIPMENT_ACTION,
	.attack = {
		.function = ft_weapon_attack,
		.damage_type = DAMAGE_TYPE_BLUDGEONING,
		.stat = STAT_STR,
		.effect_type = 0,
		.effect_dice_amount = 1,
		.effect_dice_faces = 10,
		.effect_secund_dice_amount = 0,
		.effect_secund_dice_faces = 0,
		.bonus_mod = 0,
	},
	.skill_mod = INITIALIZE_SKILLSM,
	.resistance = INITIALIZE_RESISTANCE,
	.flat_dr = INITIALIZE_RESISTANCE,
	.skill_advantage = INITIALIZE_SKILLSM,
	.save = INITIALIZE_SAVES,
	.save_advantage = INITIALIZE_SAVES,
	.type = WTYPE_CLUB,
	.dex_ac_max_bonus = 0,
	.ac = 0,
	.str = 0,
	.dex = 0,
	.con = 0,
	.inte = 0,
	.wis = 0,
	.cha = 0,
	.initiative = 0,
	.effect_type = 0,
	.effect_dice_amount = 0,
	.effect_dice_faces = 0,
	.bonus_mod = 0,
	.slot = SLOT_TWO_HANDED_WEAPON,
};

static const t_equipment_id CLAW =
{
	.name = "claw",
	.projectile_name = ft_nullptr,
	.equipment_id = CLAW_ID,
	.action_01 = INITIALIZE_EQUIPMENT_ACTION,
	.action_02 = INITIALIZE_EQUIPMENT_ACTION,
	.attack = {
		.function = ft_weapon_attack,
		.damage_type = DAMAGE_TYPE_SLASHING,
		.stat = STAT_DEX,
		.effect_type = 0,
		.effect_dice_amount = 1,
		.effect_dice_faces = 6,
		.effect_secund_dice_amount = 0,
		.effect_secund_dice_faces = 0,
		.bonus_mod = 0,
	},
	.skill_mod = INITIALIZE_SKILLSM,
	.resistance = INITIALIZE_RESISTANCE,
	.flat_dr = INITIALIZE_RESISTANCE,
	.skill_advantage = INITIALIZE_SKILLSM,
	.save = INITIALIZE_SAVES,
	.save_advantage = INITIALIZE_SAVES,
	.type = WTYPE_CLAW,
	.dex_ac_max_bonus = 0,
	.ac = 0,
	.str = 0,
	.dex = 0,
	.con = 0,
	.inte = 0,
	.wis = 0,
	.cha = 0,
	.initiative = 0,
	.effect_type = 0,
	.effect_dice_amount = 0,
	.effect_dice_faces = 0,
	.bonus_mod = 0,
	.slot = SLOT_WEAPON,
};

static const t_equipment_id CLAW_OH =
{
	.name = "claw",
	.projectile_name = ft_nullptr,
	.equipment_id = CLAW_ID,
	.action_01 = INITIALIZE_EQUIPMENT_ACTION,
	.action_02 = INITIALIZE_EQUIPMENT_ACTION,
	.attack = {
		.function = ft_weapon_attack,
		.damage_type = DAMAGE_TYPE_SLASHING,
		.stat = STAT_DEX,
		.effect_type = 0,
		.effect_dice_amount = 1,
		.effect_dice_faces = 6,
		.effect_secund_dice_amount = 0,
		.effect_secund_dice_faces = 0,
		.bonus_mod = 0,
	},
	.skill_mod = INITIALIZE_SKILLSM,
	.resistance = INITIALIZE_RESISTANCE,
	.flat_dr = INITIALIZE_RESISTANCE,
	.skill_advantage = INITIALIZE_SKILLSM,
	.save = INITIALIZE_SAVES,
	.save_advantage = INITIALIZE_SAVES,
	.type = WTYPE_CLAW,
	.dex_ac_max_bonus = 0,
	.ac = 0,
	.str = 0,
	.dex = 0,
	.con = 0,
	.inte = 0,
	.wis = 0,
	.cha = 0,
	.initiative = 0,
	.effect_type = 0,
	.effect_dice_amount = 0,
	.effect_dice_faces = 0,
	.bonus_mod = 0,
	.slot = SLOT_OFFHAND_WEAPON,
};

static const t_equipment_id GHOSTLY_SWORD =
{
	.name = "ghostly sword",
	.projectile_name = ft_nullptr,
	.equipment_id = STEEL_SWORD_ID,
	.action_01 = INITIALIZE_EQUIPMENT_ACTION,
	.action_02 = INITIALIZE_EQUIPMENT_ACTION,
	.attack = {
		.function = ft_weapon_attack,
		.damage_type = DAMAGE_TYPE_NECROTIC,
		.stat = FINESSE,
		.effect_type = 0,
		.effect_dice_amount = 1,
		.effect_dice_faces = 8,
		.effect_secund_dice_amount = 1,
		.effect_secund_dice_faces = 6,
		.bonus_mod = 0,
	},
	.skill_mod = INITIALIZE_SKILLSM,
	.resistance = INITIALIZE_RESISTANCE,
	.flat_dr = INITIALIZE_RESISTANCE,
	.skill_advantage = INITIALIZE_SKILLSM,
	.save = INITIALIZE_SAVES,
	.save_advantage = INITIALIZE_SAVES,
	.type = WTYPE_SHORTSWORD,
	.dex_ac_max_bonus = 0,
	.ac = 0,
	.str = 0,
	.dex = 0,
	.con = 0,
	.inte = 0,
	.wis = 0,
	.cha = 0,
	.initiative = 0,
	.effect_type = 0,
	.effect_dice_amount = 0,
	.effect_dice_faces = 0,
	.bonus_mod = 0,
	.slot = SLOT_WEAPON | SLOT_OFFHAND_WEAPON,
};

#endif
