#ifndef MELEE_WEAPONS_H
# define MELEE_WEAPONS_H

#include "dnd_tools.hpp"
#include <stddef.h>
#include "character.hpp"
#include "identification.hpp"
#include "initialize.hpp"
#include "libft/CPP_class/class_nullptr.hpp"

void    ft_weapon_attack(t_char * info, t_equipment_id *weapon, int offhand);

static const t_equipment_id STEEL_SWORD =
{
    .name = "steel sword",
    .projectile_name = ft_nullptr,
    .equipment_id = STEEL_SWORD_ID,
    .action_01 = INITIALIZE_EQUIPMENT_EFFECT,
    .action_02 = INITIALIZE_EQUIPMENT_EFFECT,
    .attack =
    {
        .function = ft_weapon_attack,
        .damage_type = DAMAGE_TYPE_SLASHING,
        .stat = FINESSE,
        .effect_type = NONE,
        .effect_dice_amount = 1,
        .effect_dice_faces = 8,
        .effect_secund_dice_amount = 1,
        .effect_secund_dice_faces = 6,
        .bonus_mod = 0,
    },
    .skill_mod = INITIALIZE_SKILLS,
    .resistance = INITIALIZE_RESISTANCE,
    .flat_dr = INITIALIZE_RESISTANCE,
    .skill_advantage = INITIALIZE_SKILLS,
    .save = INITIALIZE_SAVES,
    .save_advantage = INITIALIZE_SAVES,
    .crit_attack_fail_bonus = 0,
    .crit_attack_succes_bonus = 0,
    .type = WTYPE_SHORTSWORD,
    .dex_ac_max_bonus = 0,
    .ac = 0,
    .str = 0,
    .dex = 0,
    .con = 0,
    .inte = 0,
    .wis = 0,
    .cha = 0,
    .initiative = 0,
    .effect_id = 0,
    .effect_type = 0,
    .effect_dice_amount = 0,
    .effect_dice_faces = 0,
    .bonus_mod = 0,
    .slot = SLOT_WEAPON | SLOT_OFFHAND_WEAPON,
};

static const t_equipment_id WOODEN_SHIELD =
{
    .name = "wooden shield",
    .projectile_name = ft_nullptr,
    .equipment_id = STEEL_SWORD_ID,
    .action_01 = INITIALIZE_EQUIPMENT_EFFECT,
    .action_02 = INITIALIZE_EQUIPMENT_EFFECT,
    .attack = INITIALIZE_EQUIPMENT_ACTION,
    .skill_mod = INITIALIZE_SKILLS,
    .resistance = INITIALIZE_RESISTANCE,
    .flat_dr = INITIALIZE_RESISTANCE,
    .skill_advantage = INITIALIZE_SKILLS,
    .save = INITIALIZE_SAVES,
    .save_advantage = INITIALIZE_SAVES,
    .crit_attack_fail_bonus = 0,
    .crit_attack_succes_bonus = 0,
    .type = WTYPE_SHORTSWORD,
    .dex_ac_max_bonus = 0,
    .ac = 2,
    .str = 0,
    .dex = 0,
    .con = 0,
    .inte = 0,
    .wis = 0,
    .cha = 0,
    .initiative = 0,
    .effect_id = 0,
    .effect_type = 0,
    .effect_dice_amount = 0,
    .effect_dice_faces = 0,
    .bonus_mod = 0,
    .slot = SLOT_OFFHAND_WEAPON,
};

static const t_equipment_id STEEL_BATTLE_AXE =
{
    .name = "steel battle axe",
    .projectile_name = ft_nullptr,
    .equipment_id = STEEL_BATTLE_AXE_ID,
    .action_01 = INITIALIZE_EQUIPMENT_EFFECT,
    .action_02 = INITIALIZE_EQUIPMENT_EFFECT,
    .attack =
    {
        .function = ft_weapon_attack,
        .damage_type = DAMAGE_TYPE_SLASHING,
        .stat = STAT_STR,
        .effect_type = NONE,
        .effect_dice_amount = 1,
        .effect_dice_faces = 10,
        .effect_secund_dice_amount = 1,
        .effect_secund_dice_faces = 8,
        .bonus_mod = 0,
    },
    .skill_mod = INITIALIZE_SKILLS,
    .resistance = INITIALIZE_RESISTANCE,
    .flat_dr = INITIALIZE_RESISTANCE,
    .skill_advantage = INITIALIZE_SKILLS,
    .save = INITIALIZE_SAVES,
    .save_advantage = INITIALIZE_SAVES,
    .crit_attack_fail_bonus = 0,
    .crit_attack_succes_bonus = 0,
    .type = WTYPE_BATTLEAXE,
    .dex_ac_max_bonus = 0,
    .ac = 0,
    .str = 0,
    .dex = 0,
    .con = 0,
    .inte = 0,
    .wis = 0,
    .cha = 0,
    .initiative = 0,
    .effect_id = 0,
    .effect_type = 0,
    .effect_dice_amount = 0,
    .effect_dice_faces = 0,
    .bonus_mod = 0,
        .slot = SLOT_WEAPON | SLOT_OFFHAND_WEAPON,
};

static const t_equipment_id LONGSWORD =
{
        .name = "longsword",
        .projectile_name = ft_nullptr,
        .equipment_id = LONGSWORD_ID,
        .action_01 = INITIALIZE_EQUIPMENT_EFFECT,
        .action_02 = INITIALIZE_EQUIPMENT_EFFECT,
        .attack =
        {
                .function = ft_weapon_attack,
                .damage_type = DAMAGE_TYPE_SLASHING,
                .stat = FINESSE,
                .effect_type = NONE,
                .effect_dice_amount = 1,
                .effect_dice_faces = 8,
                .effect_secund_dice_amount = 1,
                .effect_secund_dice_faces = 10,
                .bonus_mod = 0,
        },
        .skill_mod = INITIALIZE_SKILLS,
        .resistance = INITIALIZE_RESISTANCE,
        .flat_dr = INITIALIZE_RESISTANCE,
        .skill_advantage = INITIALIZE_SKILLS,
        .save = INITIALIZE_SAVES,
        .save_advantage = INITIALIZE_SAVES,
        .crit_attack_fail_bonus = 0,
        .crit_attack_succes_bonus = 0,
        .type = WTYPE_LONGSWORD,
        .dex_ac_max_bonus = 0,
        .ac = 0,
        .str = 0,
        .dex = 0,
        .con = 0,
        .inte = 0,
        .wis = 0,
        .cha = 0,
        .initiative = 0,
        .effect_id = 0,
        .effect_type = 0,
        .effect_dice_amount = 0,
        .effect_dice_faces = 0,
        .bonus_mod = 0,
        .slot = SLOT_WEAPON | SLOT_OFFHAND_WEAPON,
};

static const t_equipment_id WOODEN_CLUB =
{
    .name = "wooden club",
    .projectile_name = ft_nullptr,
    .equipment_id = WOODEN_CLUB_ID,
    .action_01 = INITIALIZE_EQUIPMENT_EFFECT,
    .action_02 = INITIALIZE_EQUIPMENT_EFFECT,
    .attack =
    {
        .function = ft_weapon_attack,
        .damage_type = DAMAGE_TYPE_BLUDGEONING,
        .stat = STAT_STR,
        .effect_type = NONE,
        .effect_dice_amount = 1,
        .effect_dice_faces = 10,
        .effect_secund_dice_amount = 0,
        .effect_secund_dice_faces = 0,
        .bonus_mod = 0,
    },
    .skill_mod = INITIALIZE_SKILLS,
    .resistance = INITIALIZE_RESISTANCE,
    .flat_dr = INITIALIZE_RESISTANCE,
    .skill_advantage = INITIALIZE_SKILLS,
    .save = INITIALIZE_SAVES,
    .save_advantage = INITIALIZE_SAVES,
    .crit_attack_fail_bonus = 0,
    .crit_attack_succes_bonus = 0,
    .type = WTYPE_CLUB,
    .dex_ac_max_bonus = 0,
    .ac = 0,
    .str = 0,
    .dex = 0,
    .con = 0,
    .inte = 0,
    .wis = 0,
    .cha = 0,
    .initiative = 0,
    .effect_id = 0,
    .effect_type = 0,
    .effect_dice_amount = 0,
    .effect_dice_faces = 0,
    .bonus_mod = 0,
    .slot = SLOT_TWO_HANDED_WEAPON,
};

static const t_equipment_id CLAW =
{
    .name = "claw",
    .projectile_name = ft_nullptr,
    .equipment_id = CLAW_ID,
    .action_01 = INITIALIZE_EQUIPMENT_EFFECT,
    .action_02 = INITIALIZE_EQUIPMENT_EFFECT,
    .attack =
    {
        .function = ft_weapon_attack,
        .damage_type = DAMAGE_TYPE_SLASHING,
        .stat = STAT_DEX,
        .effect_type = NONE,
        .effect_dice_amount = 1,
        .effect_dice_faces = 6,
        .effect_secund_dice_amount = 0,
        .effect_secund_dice_faces = 0,
        .bonus_mod = 0,
    },
    .skill_mod = INITIALIZE_SKILLS,
    .resistance = INITIALIZE_RESISTANCE,
    .flat_dr = INITIALIZE_RESISTANCE,
    .skill_advantage = INITIALIZE_SKILLS,
    .save = INITIALIZE_SAVES,
    .save_advantage = INITIALIZE_SAVES,
    .crit_attack_fail_bonus = 0,
    .crit_attack_succes_bonus = 0,
    .type = WTYPE_CLAW,
    .dex_ac_max_bonus = 0,
    .ac = 0,
    .str = 2,
    .dex = 2,
    .con = 0,
    .inte = 0,
    .wis = 0,
    .cha = 0,
    .initiative = 0,
    .effect_id = 0,
    .effect_type = 0,
    .effect_dice_amount = 0,
    .effect_dice_faces = 0,
    .bonus_mod = 0,
    .slot = SLOT_WEAPON,
};

static const t_equipment_id CLAW_OH =
{
    .name = "claw",
    .projectile_name = ft_nullptr,
    .equipment_id = CLAW_ID,
    .action_01 = INITIALIZE_EQUIPMENT_EFFECT,
    .action_02 = INITIALIZE_EQUIPMENT_EFFECT,
    .attack =
    {
        .function = ft_weapon_attack,
        .damage_type = DAMAGE_TYPE_NECROTIC,
        .stat = STAT_DEX,
        .effect_type = NONE,
        .effect_dice_amount = 1,
        .effect_dice_faces = 6,
        .effect_secund_dice_amount = 0,
        .effect_secund_dice_faces = 0,
        .bonus_mod = 0,
    },
    .skill_mod = INITIALIZE_SKILLS,
    .resistance = INITIALIZE_RESISTANCE,
    .flat_dr = INITIALIZE_RESISTANCE,
    .skill_advantage = INITIALIZE_SKILLS,
    .save = INITIALIZE_SAVES,
    .save_advantage = INITIALIZE_SAVES,
    .crit_attack_fail_bonus = 0,
    .crit_attack_succes_bonus = 0,
    .type = WTYPE_CLAW,
    .dex_ac_max_bonus = 0,
    .ac = 0,
    .str = 0,
    .dex = 0,
    .con = 0,
    .inte = 0,
    .wis = 0,
    .cha = 0,
    .initiative = 0,
    .effect_id = 0,
    .effect_type = 0,
    .effect_dice_amount = 0,
    .effect_dice_faces = 0,
    .bonus_mod = 0,
    .slot = SLOT_OFFHAND_WEAPON,
};

static const t_equipment_id GHOSTLY_SWORD =
{
    .name = "ghostly sword",
    .projectile_name = ft_nullptr,
    .equipment_id = STEEL_SWORD_ID,
    .action_01 = INITIALIZE_EQUIPMENT_EFFECT,
    .action_02 = INITIALIZE_EQUIPMENT_EFFECT,
    .attack =
    {
        .function = ft_weapon_attack,
        .damage_type = DAMAGE_TYPE_NECROTIC,
        .stat = FINESSE,
        .effect_type = NONE,
        .effect_dice_amount = 1,
        .effect_dice_faces = 8,
        .effect_secund_dice_amount = 1,
        .effect_secund_dice_faces = 6,
        .bonus_mod = 0,
    },
    .skill_mod = INITIALIZE_SKILLS,
    .resistance = INITIALIZE_RESISTANCE,
    .flat_dr = INITIALIZE_RESISTANCE,
    .skill_advantage = INITIALIZE_SKILLS,
    .save = INITIALIZE_SAVES,
    .save_advantage = INITIALIZE_SAVES,
    .crit_attack_fail_bonus = 0,
    .crit_attack_succes_bonus = 0,
    .type = WTYPE_SHORTSWORD,
    .dex_ac_max_bonus = 0,
    .ac = 0,
    .str = 0,
    .dex = 0,
    .con = 0,
    .inte = 0,
    .wis = 0,
    .cha = 0,
    .initiative = 0,
    .effect_id = 0,
    .effect_type = 0,
    .effect_dice_amount = 0,
    .effect_dice_faces = 0,
    .bonus_mod = 0,
    .slot = SLOT_WEAPON | SLOT_OFFHAND_WEAPON,
};

static const t_equipment_id FELBEAST_CLAW =
{
    .name = "felbeast claw",
    .projectile_name = ft_nullptr,
    .equipment_id = FELBEAST_CLAW_ID,
    .action_01 =
    {
        .function = ft_fel_poison_attack_effects,
        .damage_type = DAMAGE_TYPE_NECROTIC,
        .stat = STAT_CON,
        .effect_type = ETYPE_FEL_POISON,
        .effect_dice_amount = 2,
        .effect_dice_faces = 6,
        .effect_secund_dice_amount = 0,
        .effect_secund_dice_faces = 0,
        .bonus_mod = 15,
    },
    .action_02 = INITIALIZE_EQUIPMENT_EFFECT,
    .attack =
    {
        .function = ft_weapon_attack,
        .damage_type = DAMAGE_TYPE_NECROTIC,
        .stat = FINESSE,
        .effect_type = NONE,
        .effect_dice_amount = 1,
        .effect_dice_faces = 6,
        .effect_secund_dice_amount = 1,
        .effect_secund_dice_faces = 6,
        .bonus_mod = 0,
    },
    .skill_mod = INITIALIZE_SKILLS,
    .resistance = INITIALIZE_RESISTANCE,
    .flat_dr = INITIALIZE_RESISTANCE,
    .skill_advantage = INITIALIZE_SKILLS,
    .save = INITIALIZE_SAVES,
    .save_advantage = INITIALIZE_SAVES,
    .crit_attack_fail_bonus = 0,
    .crit_attack_succes_bonus = 0,
    .type = WTYPE_CLAW,
    .dex_ac_max_bonus = 0,
    .ac = 0,
    .str = 0,
    .dex = 0,
    .con = 0,
    .inte = 0,
    .wis = 0,
    .cha = 0,
    .initiative = 0,
    .effect_id = 0,
    .effect_type = 0,
    .effect_dice_amount = 0,
    .effect_dice_faces = 0,
    .bonus_mod = 0,
    .slot = SLOT_WEAPON | SLOT_OFFHAND_WEAPON,
};

static const t_equipment_id FELBEAST_CLAW_OH =
{
    .name = "felbeast claw oh",
    .projectile_name = ft_nullptr,
    .equipment_id = FELBEAST_CLAW_OH_ID,
    .action_01 =
    {
        .function = ft_fel_poison_attack_effects,
        .damage_type = DAMAGE_TYPE_NECROTIC,
        .stat = STAT_CON,
        .effect_type = ETYPE_FEL_POISON,
        .effect_dice_amount = 2,
        .effect_dice_faces = 6,
        .effect_secund_dice_amount = 0,
        .effect_secund_dice_faces = 0,
        .bonus_mod = 4,
    },
    .action_02 = INITIALIZE_EQUIPMENT_EFFECT,
    .attack =
    {
        .function = ft_weapon_attack,
        .damage_type = DAMAGE_TYPE_NECROTIC,
        .stat = FINESSE,
        .effect_type = NONE,
        .effect_dice_amount = 1,
        .effect_dice_faces = 6,
        .effect_secund_dice_amount = 1,
        .effect_secund_dice_faces = 6,
        .bonus_mod = 0,
    },
    .skill_mod = INITIALIZE_SKILLS,
    .resistance = INITIALIZE_RESISTANCE,
    .flat_dr = INITIALIZE_RESISTANCE,
    .skill_advantage = INITIALIZE_SKILLS,
    .save = INITIALIZE_SAVES,
    .save_advantage = INITIALIZE_SAVES,
    .crit_attack_fail_bonus = 0,
    .crit_attack_succes_bonus = 0,
    .type = WTYPE_CLAW,
    .dex_ac_max_bonus = 0,
    .ac = 0,
    .str = 0,
    .dex = 0,
    .con = 0,
    .inte = 0,
    .wis = 0,
    .cha = 0,
    .initiative = 0,
    .effect_id = 0,
    .effect_type = 0,
    .effect_dice_amount = 0,
    .effect_dice_faces = 0,
    .bonus_mod = 0,
    .slot = SLOT_WEAPON | SLOT_OFFHAND_WEAPON,
};

static const t_equipment_id ANCIENT_PREDATORY_BEAST_CLAW =
{
    .name = "ancient predatory beast claw",
    .projectile_name = ft_nullptr,
    .equipment_id = ANCIENT_PREDATORY_BEAST_CLAW_ID,
    .action_01 =
    {
        .function = ft_ancient_predatory_beast_attack_effects,
        .damage_type = DAMAGE_TYPE_SLASHING,
        .stat = ft_nullptr,
        .effect_type = ETYPE_ANCIENT_PREDATORY_BEAST_MULTI_ATTACK,
        .effect_dice_amount = 2,
        .effect_dice_faces = 6,
        .effect_secund_dice_amount = 0,
        .effect_secund_dice_faces = 0,
        .bonus_mod = 4,
    },
    .action_02 = INITIALIZE_EQUIPMENT_EFFECT,
    .attack =
    {
        .function = ft_weapon_attack,
        .damage_type = DAMAGE_TYPE_SLASHING,
        .stat = FINESSE,
        .effect_type = NONE,
        .effect_dice_amount = 1,
        .effect_dice_faces = 6,
        .effect_secund_dice_amount = 1,
        .effect_secund_dice_faces = 6,
        .bonus_mod = 0,
    },
    .skill_mod = INITIALIZE_SKILLS,
    .resistance = INITIALIZE_RESISTANCE,
    .flat_dr = INITIALIZE_RESISTANCE,
    .skill_advantage = INITIALIZE_SKILLS,
    .save = INITIALIZE_SAVES,
    .save_advantage = INITIALIZE_SAVES,
    .crit_attack_fail_bonus = 0,
    .crit_attack_succes_bonus = 0,
    .type = WTYPE_CLAW,
    .dex_ac_max_bonus = 0,
    .ac = 0,
    .str = 0,
    .dex = 0,
    .con = 0,
    .inte = 0,
    .wis = 0,
    .cha = 0,
    .initiative = 0,
    .effect_id = 0,
    .effect_type = 0,
    .effect_dice_amount = 0,
    .effect_dice_faces = 0,
    .bonus_mod = 0,
    .slot = SLOT_WEAPON | SLOT_OFFHAND_WEAPON,
};

static const t_equipment_id SHADOW_CLAW =
{
        .name = "shadow claw",
        .projectile_name = ft_nullptr,
        .equipment_id = SHADOW_CLAW_ID,
    .action_01 =
    {
        .function = ft_shadow_claw_effect,
        .damage_type = DAMAGE_TYPE_NECROTIC,
        .stat = ft_nullptr,
        .effect_type = ETYPE_ANCIENT_PREDATORY_BEAST_MULTI_ATTACK,
        .effect_dice_amount = 0,
        .effect_dice_faces = 10,
        .effect_secund_dice_amount = 0,
        .effect_secund_dice_faces = 0,
        .bonus_mod = 1,
    },
    .action_02 = INITIALIZE_EQUIPMENT_EFFECT,
    .attack =
    {
        .function = ft_weapon_attack,
        .damage_type = DAMAGE_TYPE_SLASHING,
        .stat = FINESSE,
        .effect_type = NONE,
        .effect_dice_amount = 2,
        .effect_dice_faces = 6,
        .effect_secund_dice_amount = 0,
        .effect_secund_dice_faces = 0,
        .bonus_mod = 3,
    },
    .skill_mod = INITIALIZE_SKILLS,
    .resistance = INITIALIZE_RESISTANCE,
    .flat_dr = INITIALIZE_RESISTANCE,
    .skill_advantage = INITIALIZE_SKILLS,
    .save = INITIALIZE_SAVES,
    .save_advantage = INITIALIZE_SAVES,
    .crit_attack_fail_bonus = 2,
    .crit_attack_succes_bonus = 5,
    .type = WTYPE_CLAW,
    .dex_ac_max_bonus = 0,
    .ac = 0,
    .str = 0,
    .dex = 0,
    .con = 0,
    .inte = 0,
    .wis = 0,
    .cha = 0,
    .initiative = 0,
    .effect_id = 0,
    .effect_type = 0,
    .effect_dice_amount = 0,
    .effect_dice_faces = 0,
    .bonus_mod = 0,
        .slot = SLOT_WEAPON | SLOT_OFFHAND_WEAPON,
};

static const t_equipment_id NIGHTMARE_CLAW =
{
    .name = "nightmare claw",
    .projectile_name = ft_nullptr,
    .equipment_id = NIGHTMARE_CLAW_ID,
    .action_01 =
    {
        .function = ft_nightmare_claw_effect,
        .damage_type = DAMAGE_TYPE_PSYCHIC,
        .stat = ft_nullptr,
        .effect_type = NONE,
        .effect_dice_amount = 0,
        .effect_dice_faces = 0,
        .effect_secund_dice_amount = 0,
        .effect_secund_dice_faces = 0,
        .bonus_mod = 0,
    },
    .action_02 = INITIALIZE_EQUIPMENT_EFFECT,
    .attack =
    {
        .function = ft_weapon_attack,
        .damage_type = DAMAGE_TYPE_SLASHING,
        .stat = FINESSE,
        .effect_type = NONE,
        .effect_dice_amount = 2,
        .effect_dice_faces = 6,
        .effect_secund_dice_amount = 0,
        .effect_secund_dice_faces = 0,
        .bonus_mod = 3,
    },
    .skill_mod = INITIALIZE_SKILLS,
    .resistance = INITIALIZE_RESISTANCE,
    .flat_dr = INITIALIZE_RESISTANCE,
    .skill_advantage = INITIALIZE_SKILLS,
    .save = INITIALIZE_SAVES,
    .save_advantage = INITIALIZE_SAVES,
    .crit_attack_fail_bonus = 2,
    .crit_attack_succes_bonus = 5,
    .type = WTYPE_CLAW,
    .dex_ac_max_bonus = 0,
    .ac = 0,
    .str = 0,
    .dex = 0,
    .con = 0,
    .inte = 0,
    .wis = 0,
    .cha = 0,
    .initiative = 0,
    .effect_id = 0,
    .effect_type = 0,
    .effect_dice_amount = 0,
    .effect_dice_faces = 0,
    .bonus_mod = 0,
    .slot = SLOT_WEAPON | SLOT_OFFHAND_WEAPON,
};

static const t_equipment_id WOODEN_STAFF =
{
    .name = "wooden staff",
    .projectile_name = ft_nullptr,
    .equipment_id = STEEL_SWORD_ID,
    .action_01 = INITIALIZE_EQUIPMENT_EFFECT,
    .action_02 = INITIALIZE_EQUIPMENT_EFFECT,
    .attack =
    {
        .function = ft_weapon_attack,
        .damage_type = DAMAGE_TYPE_BLUDGEONING,
        .stat = FINESSE,
        .effect_type = NONE,
        .effect_dice_amount = 1,
        .effect_dice_faces = 8,
        .effect_secund_dice_amount = 1,
        .effect_secund_dice_faces = 6,
        .bonus_mod = 0,
    },
    .skill_mod = INITIALIZE_SKILLS,
    .resistance = INITIALIZE_RESISTANCE,
    .flat_dr = INITIALIZE_RESISTANCE,
    .skill_advantage = INITIALIZE_SKILLS,
    .save = INITIALIZE_SAVES,
    .save_advantage = INITIALIZE_SAVES,
    .crit_attack_fail_bonus = 0,
    .crit_attack_succes_bonus = 0,
    .type = WTYPE_SHORTSWORD,
    .dex_ac_max_bonus = 0,
    .ac = 0,
    .str = 0,
    .dex = 0,
    .con = 0,
    .inte = 0,
    .wis = 0,
    .cha = 0,
    .initiative = 0,
    .effect_id = 0,
    .effect_type = 0,
    .effect_dice_amount = 0,
    .effect_dice_faces = 0,
    .bonus_mod = 0,
    .slot = SLOT_WEAPON | SLOT_OFFHAND_WEAPON,
};

static const t_equipment_id FELGUARD_POSIONED_AXE =
{
    .name = "poisoned axe",
    .projectile_name = ft_nullptr,
    .equipment_id = FELGUARD_POSIONED_AXE_ID,
    .action_01 =
    {
        .function = ft_fel_poison_attack_effects,
        .damage_type = DAMAGE_TYPE_NECROTIC,
        .stat = STAT_CON,
        .effect_type = ETYPE_FEL_POISON,
        .effect_dice_amount = 2,
        .effect_dice_faces = 6,
        .effect_secund_dice_amount = 0,
        .effect_secund_dice_faces = 0,
        .bonus_mod = 4,
    },
    .action_02 = INITIALIZE_EQUIPMENT_EFFECT,
    .attack =
    {
        .function = ft_weapon_attack,
        .damage_type = DAMAGE_TYPE_NECROTIC,
        .stat = FINESSE,
        .effect_type = NONE,
        .effect_dice_amount = 1,
        .effect_dice_faces = 6,
        .effect_secund_dice_amount = 1,
        .effect_secund_dice_faces = 6,
        .bonus_mod = 0,
    },
    .skill_mod = INITIALIZE_SKILLS,
    .resistance = INITIALIZE_RESISTANCE,
    .flat_dr = INITIALIZE_RESISTANCE,
    .skill_advantage = INITIALIZE_SKILLS,
    .save = INITIALIZE_SAVES,
    .save_advantage = INITIALIZE_SAVES,
    .crit_attack_fail_bonus = 0,
    .crit_attack_succes_bonus = 0,
    .type = WTYPE_CLAW,
    .dex_ac_max_bonus = 0,
    .ac = 0,
    .str = 0,
    .dex = 0,
    .con = 0,
    .inte = 0,
    .wis = 0,
    .cha = 0,
    .initiative = 0,
    .effect_id = 0,
    .effect_type = 0,
    .effect_dice_amount = 0,
    .effect_dice_faces = 0,
    .bonus_mod = 0,
    .slot = SLOT_WEAPON | SLOT_OFFHAND_WEAPON,
};

static const t_equipment_id MITHRIL_AXE =
{
    .name = "mithril axe",
    .projectile_name = ft_nullptr,
    .equipment_id = MITHRIL_AXE_ID,
    .action_01 = INITIALIZE_EQUIPMENT_EFFECT,
    .action_02 = INITIALIZE_EQUIPMENT_EFFECT,
    .attack =
    {
        .function = ft_weapon_attack,
        .damage_type = DAMAGE_TYPE_SLASHING,
        .stat = STAT_STR,
        .effect_type = NONE,
        .effect_dice_amount = 2,
        .effect_dice_faces = 6,
        .effect_secund_dice_amount = 0,
        .effect_secund_dice_faces = 0,
        .bonus_mod = 0,
    },
    .skill_mod = INITIALIZE_SKILLS,
    .resistance = INITIALIZE_RESISTANCE,
    .flat_dr = INITIALIZE_RESISTANCE,
    .skill_advantage = INITIALIZE_SKILLS,
    .save = INITIALIZE_SAVES,
    .save_advantage = INITIALIZE_SAVES,
    .crit_attack_fail_bonus = 0,
    .crit_attack_succes_bonus = 0,
    .type = WTYPE_BATTLEAXE,
    .dex_ac_max_bonus = 0,
    .ac = 0,
    .str = 0,
    .dex = 0,
    .con = 0,
    .inte = 0,
    .wis = 0,
    .cha = 0,
    .initiative = 0,
    .effect_id = 0,
    .effect_type = 0,
    .effect_dice_amount = 0,
    .effect_dice_faces = 0,
    .bonus_mod = 0,
    .slot = SLOT_TWO_HANDED_WEAPON,
};

static const t_equipment_id MANNOROTH_GLAIVE =
{
    .name = "mannoroth glaive",
    .projectile_name = ft_nullptr,
    .equipment_id = MANNOROTH_GLAIVE_ID,
    .action_01 = INITIALIZE_EQUIPMENT_EFFECT,
    .action_02 = INITIALIZE_EQUIPMENT_EFFECT,
    .attack =
    {
        .function = ft_weapon_attack,
        .damage_type = DAMAGE_TYPE_SLASHING,
        .stat = STAT_STR,
        .effect_type = NONE,
        .effect_dice_amount = 2,
        .effect_dice_faces = 10,
        .effect_secund_dice_amount = 0,
        .effect_secund_dice_faces = 0,
        .bonus_mod = 0,
    },
    .skill_mod = INITIALIZE_SKILLS,
    .resistance = INITIALIZE_RESISTANCE,
    .flat_dr = INITIALIZE_RESISTANCE,
    .skill_advantage = INITIALIZE_SKILLS,
    .save = INITIALIZE_SAVES,
    .save_advantage = INITIALIZE_SAVES,
    .crit_attack_fail_bonus = 0,
    .crit_attack_succes_bonus = 0,
    .type = WTYPE_GLAIVE,
    .dex_ac_max_bonus = 0,
    .ac = 0,
    .str = 0,
    .dex = 0,
    .con = 0,
    .inte = 0,
    .wis = 0,
    .cha = 0,
    .initiative = 0,
    .effect_id = 0,
    .effect_type = 0,
    .effect_dice_amount = 0,
    .effect_dice_faces = 0,
    .bonus_mod = 0,
    .slot = SLOT_TWO_HANDED_WEAPON,
};

#endif
