#ifndef RANGED_WEAPONS_H
# define RANGED_WEAPONS_H

# include <stddef.h>
# include "character.hpp"
# include "dnd_tools.hpp"
# include "identification.hpp"
# include "initialize.hpp"
#include "libft/CPP_class/class_nullptr.hpp"

void    ft_weapon_attack(t_char *info, t_equipment_id *weapon, int offhand);

static const t_equipment_id WOODEN_BOW =
{
    .name = "wooden bow",
    .projectile_name = "arrow",
    .equipment_id = WOODEN_BOW_ID,
    .action_01 = INITIALIZE_EQUIPMENT_EFFECT,
    .action_02 = INITIALIZE_EQUIPMENT_EFFECT,
    .attack =
    {
        .function = ft_weapon_attack,
        .damage_type = DAMAGE_TYPE_PIERCING,
        .stat = STAT_DEX,
        .effect_type = NONE,
        .effect_dice_amount = 1,
        .effect_dice_faces = 8,
        .effect_secund_dice_amount = 0,
        .effect_secund_dice_faces = 0,
        .bonus_mod = 0,
    },
    .skill_mod = INITIALIZE_SKILLS,
    .resistance = INITIALIZE_RESISTANCE,
    .flat_dr = INITIALIZE_RESISTANCE,
    .skill_advantage = INITIALIZE_SKILLS,
    .save = INITIALIZE_SAVES,
    .save_advantage = INITIALIZE_SAVES,
    .crit_attack_fail_bonus = 0,
    .crit_attack_succes_bonus = 0,
    .type = WTYPE_SHORTBOW,
    .dex_ac_max_bonus = 0,
    .ac = 0,
    .str = 0,
    .dex = 0,
    .con = 0,
    .inte = 0,
    .wis = 0,
    .cha = 0,
    .initiative = 0,
    .effect_id = 0,
    .effect_type = 0,
    .effect_dice_amount = 0,
    .effect_dice_faces = 0,
    .bonus_mod = 0,
    .slot = SLOT_RANGED_WEAPON,
};

static const t_equipment_id CHAOS_WAND =
{
    .name = "chaos wand",
    .projectile_name = "chaos bolt",
    .equipment_id = CHAOS_WAND_ID,
    .action_01 = INITIALIZE_EQUIPMENT_EFFECT,
    .action_02 = INITIALIZE_EQUIPMENT_EFFECT,
    .attack =
    {
        .function = ft_weapon_attack,
        .damage_type = DAMAGE_TYPE_NECROTIC,
        .stat = STAT_INT,
        .effect_type = NONE,
        .effect_dice_amount = 2,
        .effect_dice_faces = 4,
        .effect_secund_dice_amount = 0,
        .effect_secund_dice_faces = 0,
        .bonus_mod = 0,
    },
    .skill_mod = INITIALIZE_SKILLS,
    .resistance = INITIALIZE_RESISTANCE,
    .flat_dr = INITIALIZE_RESISTANCE,
    .skill_advantage = INITIALIZE_SKILLS,
    .save = INITIALIZE_SAVES,
    .save_advantage = INITIALIZE_SAVES,
    .crit_attack_fail_bonus = 0,
    .crit_attack_succes_bonus = 0,
    .type = WTYPE_WAND,
    .dex_ac_max_bonus = 0,
    .ac = 0,
    .str = 0,
    .dex = 0,
    .con = 0,
    .inte = 0,
    .wis = 0,
    .cha = 0,
    .initiative = 0,
    .effect_id = 0,
    .effect_type = 0,
    .effect_dice_amount = 0,
    .effect_dice_faces = 0,
    .bonus_mod = 0,
    .slot = SLOT_RANGED_WEAPON,
};

static const t_equipment_id WAND_OF_DRAINING =
{
    .name = "wand of draining",
    .projectile_name = "draining bolt",
    .equipment_id = WAND_OF_DRAINING_ID,
    .action_01 =
    {
        .function = ft_strength_drain,
        .damage_type = DAMAGE_TYPE_THUNDER,
        .stat = STAT_INT,
        .effect_type = NONE,
        .effect_dice_amount = 15,
        .effect_dice_faces = 0,
        .effect_secund_dice_amount = 0,
        .effect_secund_dice_faces = 0,
        .bonus_mod = 4,
    },
    .action_02 = INITIALIZE_EQUIPMENT_EFFECT,
    .attack =
    {
        .function = ft_weapon_attack,
        .damage_type = DAMAGE_TYPE_THUNDER,
        .stat = STAT_INT,
        .effect_type = NONE,
        .effect_dice_amount = 0,
        .effect_dice_faces = 0,
        .effect_secund_dice_amount = 0,
        .effect_secund_dice_faces = 0,
        .bonus_mod = 0,
    },
    .skill_mod = INITIALIZE_SKILLS,
    .resistance = INITIALIZE_RESISTANCE,
    .flat_dr = INITIALIZE_RESISTANCE,
    .skill_advantage = INITIALIZE_SKILLS,
    .save = INITIALIZE_SAVES,
    .save_advantage = INITIALIZE_SAVES,
    .crit_attack_fail_bonus = 0,
    .crit_attack_succes_bonus = 0,
    .type = WTYPE_WAND,
    .dex_ac_max_bonus = 0,
    .ac = 0,
    .str = 0,
    .dex = 0,
    .con = 0,
    .inte = 0,
    .wis = 0,
    .cha = 0,
    .initiative = 0,
    .effect_id = 0,
    .effect_type = 0,
    .effect_dice_amount = 0,
    .effect_dice_faces = 0,
    .bonus_mod = 0,
    .slot = SLOT_RANGED_WEAPON,
};

static const t_equipment_id SHADOW_WAND =
{
    .name = "shadow wand",
    .projectile_name = "shadow bolt",
    .equipment_id = SHADOW_WAND_ID,
    .action_01 =
    {
        .function = ft_nullptr,
        .damage_type = DAMAGE_TYPE_THUNDER,
        .stat = STAT_INT,
        .effect_type = NONE,
        .effect_dice_amount = 0,
        .effect_dice_faces = 0,
        .effect_secund_dice_amount = 0,
        .effect_secund_dice_faces = 0,
        .bonus_mod = 4,
    },
    .action_02 = INITIALIZE_EQUIPMENT_EFFECT,
    .attack =
    {
        .function = ft_weapon_attack,
        .damage_type = DAMAGE_TYPE_THUNDER,
        .stat = STAT_INT,
        .effect_type = NONE,
        .effect_dice_amount = 2,
        .effect_dice_faces = 6,
        .effect_secund_dice_amount = 0,
        .effect_secund_dice_faces = 0,
        .bonus_mod = 5,
    },
    .skill_mod = INITIALIZE_SKILLS,
    .resistance = INITIALIZE_RESISTANCE,
    .flat_dr = INITIALIZE_RESISTANCE,
    .skill_advantage = INITIALIZE_SKILLS,
    .save = INITIALIZE_SAVES,
    .save_advantage = INITIALIZE_SAVES,
    .crit_attack_fail_bonus = 0,
    .crit_attack_succes_bonus = 0,
    .type = WTYPE_WAND,
    .dex_ac_max_bonus = 0,
    .ac = 0,
    .str = 0,
    .dex = 0,
    .con = 0,
    .inte = 0,
    .wis = 0,
    .cha = 0,
    .initiative = 0,
    .effect_id = 0,
    .effect_type = 0,
    .effect_dice_amount = 0,
    .effect_dice_faces = 0,
    .bonus_mod = 0,
    .slot = SLOT_RANGED_WEAPON,
};

static const t_equipment_id SNOWBALL_WAND =
{
    .name = "snow ball wand",
    .projectile_name = "snow ball",
    .equipment_id = SNOWBALL_WAND_ID,
    .action_01 =
    {
        .function = ft_snow_goblin_attack_effects,
        .damage_type = DAMAGE_TYPE_COLD,
        .stat = STAT_CON,
        .effect_type = ETYPE_SNOWBALL_WAND_SLOW,
        .effect_dice_amount = 0,
        .effect_dice_faces = 0,
        .effect_secund_dice_amount = 0,
        .effect_secund_dice_faces = 0,
        .bonus_mod = 10,
    },
    .action_02 = INITIALIZE_EQUIPMENT_EFFECT,
    .attack =
    {
        .function = ft_weapon_attack,
        .damage_type = DAMAGE_TYPE_COLD,
        .stat = STAT_DEX,
        .effect_type = NONE,
        .effect_dice_amount = 1,
        .effect_dice_faces = 4,
        .effect_secund_dice_amount = 0,
        .effect_secund_dice_faces = 0,
        .bonus_mod = 0,
    },
    .skill_mod = INITIALIZE_SKILLS,
    .resistance = INITIALIZE_RESISTANCE,
    .flat_dr = INITIALIZE_RESISTANCE,
    .skill_advantage = INITIALIZE_SKILLS,
    .save = INITIALIZE_SAVES,
    .save_advantage = INITIALIZE_SAVES,
    .crit_attack_fail_bonus = 0,
    .crit_attack_succes_bonus = 0,
    .type = WTYPE_WAND,
    .dex_ac_max_bonus = 0,
    .ac = 0,
    .str = 0,
    .dex = 0,
    .con = 0,
    .inte = 0,
    .wis = 0,
    .cha = 0,
    .initiative = 2,
    .effect_id = 0,
    .effect_type = 0,
    .effect_dice_amount = 0,
    .effect_dice_faces = 0,
    .bonus_mod = 0,
    .slot = SLOT_RANGED_WEAPON,
};

#endif
